### ISSUE TITLE
Getting gradle issue

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [krris/Dicom-Viewer#3]
ERROR: Could not find com.android.tools.build:gradle:2.3.3.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
Required by:
    project :libraries:aFileChooser
Add Google Maven repository and sync project
Open File

build.gradle file is ::

```
/ Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        //mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

ext {
    defaultCompileSdkVersion = 25
    defaultMinSdkVersion = 16
    defaultTargetSdkVersion = 25
    defaultBuildToolsVersion = "25.0.3"
    defaultSupportLibVersion = "25.3.1"
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by hannesa2** [comment]
See my PR #2 or use directly my fork https://github.com/hannesa2/Dicom-Viewer
With it, you see it builds on CI too https://travis-ci.org/hannesa2/Dicom-Viewer

**Comment by manpreetsinghsodhi** [comment]
Tried to use your fork project. Still same issue

**Comment by hannesa2** [comment]
My fork works on CI and local on my machine. This is a sign to be located on your side.
Does it works with command line ? `./gradlew clean --refresh-dependencies`

Proxy settings ?
` ~/.gradle/gradle.properties`

Anyway it's located to your machine

**Comment by manpreetsinghsodhi** [comment]
Thanks. It was proxy issue. You can close the thread.

**Comment by hannesa2** [comment]
You are welcome. Only you or a a maintainer can close it.
